### ISSUE TITLE
translation missing: zh.label_import_issues

### ISSUE THREAD

**Issue by glatt** [juno/redmine_importer#1]
1Download the plugins named Redmine Import Issues on Redmine 2.6.6 stable,and bundle rake it(use this command:bundle exec rake redmine:plugins:migrate RAILS_ENV=production),then restart.
2Find the problem as follow(the words in the red circle ):translation missing: zh.label_import_issues.
If click that words,it will show: 404 Page Not Found Sorry, the page is not there.
3if copy en.yml(at ****\plugins\redmine_import_issues-master\config\locales)and change it name into zh.yml,restart,the trouble remains.

How could i make it ok?
![deadlink](https://cloud.githubusercontent.com/assets/13362266/8726246/9e0d3560-2c0b-11e5-904c-b3d049dc8edb.png)

**Comment by juno** [comment]
Unfortunately I don't maintain this repository anymore.
I recommend that you should use another importer plugin like a https://github.com/zh/redmine_importer.
